name = "FaunaDB"
vendor = "Fauna Inc"
slug = "faunadb"
description = "A distributed multi-model database with document and graph capabilities, accessed via its custom Fauna Query Language (FQL). Supported ACID transactions and global distribution. Service was shut down in 2025."
url = "https://fauna.com/"
type = "Multiple"
query_languages = ["FQL", "GraphQL"]
category = "Emerging"
status = "deprecated"
status_note = "Service shut down in 2025."
gdotv_support = false

[features]
active_development = 0.0
commercial_support = 1.0
live_community = 0.0
open_source = 0.5
pricing = 1.0
trendiness = 1.0
containerization = 1.0
work_as_dedicated_instance = 1.0
work_as_embedded = 0.0
testing_in_memory_version = 0.0
operating_on_linux = 1.0
operating_on_windows = 0.0
saas_offering = 1.0
automatic_updates = 0.0
client_side_caching = 0.0
data_versioning_support = 1.0
live_backups = 1.0
cluster_rebalancing = 0.0
data_distribution = 1.0
high_availability = 1.0
query_distribution = 1.0
replication_support = 1.0
data_types_defined = 0.5
logging_auditing = 1.0
object_graph_mapper = 0.0
reactive_programming = 0.0
documentation_up_to_date = 1.0
binary_protocol = 0.0
cli = 1.0
gui = 0.0
multi_database = 0.0
graph_native_data = 1.0
rest_api = 0.0
query_language = 1.0
granular_locking = 0.0
multiple_isolation_levels = 0.0
read_committed_transaction = 0.0
transaction_support = 1.0
constraints = 1.0
schema_support = 1.0
secondary_indexes = 1.0
server_side_procedures = 1.0
triggers = 0.0
authentication = 1.0
authorization = 1.0
data_encryption = 0.0
