name = "Ontotext GraphDB"
vendor = "Ontotext"
slug = "ontotext-graphdb"
description = "An RDF triplestore with ACID transactions, available in free, standard, and enterprise editions. Supports semantic reasoning and inference with configurable rule sets."
url = "https://www.ontotext.com/products/graphdb/"
license = "Proprietary"
type = "RDF"
query_languages = ["SPARQL"]
category = "Enterprise"
gdotv_support = true

[features]
active_development = 1.0
commercial_support = 1.0
live_community = 1.0
open_source = 0.0
pricing = 0.0
trendiness = 0.75
containerization = 1.0
work_as_dedicated_instance = 1.0
work_as_embedded = 1.0
testing_in_memory_version = 0.0
operating_on_linux = 1.0
operating_on_windows = 1.0
saas_offering = 0.0
automatic_updates = 0.0
client_side_caching = 0.0
data_versioning_support = 1.0
live_backups = 0.5
cluster_rebalancing = 0.0
data_distribution = 0.75
high_availability = 1.0
query_distribution = 0.75
replication_support = 1.0
data_types_defined = 1.0
logging_auditing = 1.0
object_graph_mapper = 1.0
reactive_programming = 0.0
documentation_up_to_date = 1.0
binary_protocol = 0.0
cli = 1.0
gui = 1.0
multi_database = 0.0
graph_native_data = 1.0
rest_api = 1.0
query_language = 1.0
granular_locking = 0.0
multiple_isolation_levels = 0.0
read_committed_transaction = 1.0
transaction_support = 1.0
constraints = 1.0
schema_support = 0.5
secondary_indexes = 1.0
server_side_procedures = 1.0
triggers = 0.0
authentication = 1.0
authorization = 1.0
data_encryption = 0.0
