import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const featureScore = z.number().min(0).max(1);

const databases = defineCollection({
  loader: glob({ pattern: '**/*.toml', base: './src/content/databases' }),
  schema: z.object({
    name: z.string().min(1),
    vendor: z.string().optional(),
    slug: z.string().min(1).regex(/^[a-z0-9-]+$/),
    description: z.string(),
    url: z.string().url().optional(),
    github_url: z.string().url().optional(),
    license: z.string().optional(),
    type: z.enum(['Property Graph', 'RDF', 'Multiple', 'Other']),
    kind: z.enum(['database', 'extension', 'query-engine', 'embedded', 'library']).default('database'),
    category: z.enum(['Established', 'Enterprise', 'Growing', 'Emerging']),
    status: z.enum(['active', 'inactive', 'deprecated']).default('active'),
    status_note: z.string().optional(),
    previous_vendors: z.array(z.string()).optional(),
    previous_names: z.array(z.string()).optional(),
    query_languages: z.array(z.string()).optional(),
    icon: z.string().optional(),
    gdotv_support: z.boolean(),
    gdotv_url: z.string().url().optional(),
    features: z.object({
      active_development: featureScore,
      commercial_support: featureScore,
      live_community: featureScore,
      open_source: featureScore,
      pricing: featureScore,
      trendiness: featureScore,
      containerization: featureScore,
      work_as_dedicated_instance: featureScore,
      work_as_embedded: featureScore,
      testing_in_memory_version: featureScore,
      operating_on_linux: featureScore,
      operating_on_windows: featureScore,
      saas_offering: featureScore,
      automatic_updates: featureScore,
      client_side_caching: featureScore,
      data_versioning_support: featureScore,
      live_backups: featureScore,
      cluster_rebalancing: featureScore,
      data_distribution: featureScore,
      high_availability: featureScore,
      query_distribution: featureScore,
      replication_support: featureScore,
      data_types_defined: featureScore,
      logging_auditing: featureScore,
      object_graph_mapper: featureScore,
      reactive_programming: featureScore,
      documentation_up_to_date: featureScore,
      binary_protocol: featureScore,
      cli: featureScore,
      gui: featureScore,
      multi_database: featureScore,
      graph_native_data: featureScore,
      rest_api: featureScore,
      query_language: featureScore,
      granular_locking: featureScore,
      multiple_isolation_levels: featureScore,
      read_committed_transaction: featureScore,
      transaction_support: featureScore,
      constraints: featureScore,
      schema_support: featureScore,
      secondary_indexes: featureScore,
      server_side_procedures: featureScore,
      triggers: featureScore,
      authentication: featureScore,
      authorization: featureScore,
      data_encryption: featureScore,
    }).optional(),
  }),
});

export const collections = { databases };
